on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      # sam build 
      - run: sam build -t template_no_auth.yaml 

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: ECHO 'y' | sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --on-failure DELETE --stack-name predict-no-auth --capabilities  CAPABILITY_IAM --s3-bucket lh-lambda-buckets-pod2-april20 --region ap-south-1 --image-repository ${{ secrets.ECR }} --disable-rollback y --PredictFunction may not have authorization defined, Is this okay? [y/N] y

