on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      # sam build 
      - run: sam build -t template_no_auth.yaml 

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --guided | predict-no-auth | ap-south-1 | dev | N | Y| y|y|Y|samconfig.toml|default|Y

